### ISSUE TITLE
Unable to detect UE version from .uproject file on custom UE build

### ISSUE THREAD

**Issue by mklierman** [fdefelici/vs-funreal#1]
I get the error `Cannot detect UE version from .uproject file` when loading my project. 

In my .uproject file the EngineAssociation field has the value "4.26.2-ABC". It looks like your code assumes the version field will only be 2 parts, in which case even using the standard 4.26.2 engine version would fail: [XVersion.cs](https://github.com/fdefelici/vs-funreal/blob/6d72487ba3f617027b7adc7233bf8a3e3b1b0f18/FUnreal/Sources/Utils/XVersion.cs#L10)

Perhaps that code could be updated to only read the first 2 parts of the SemVer and ignore the rest?

**Comment by fdefelici** [comment]
Hi @mklierman, thanks for reporting the issue.

I play tested with 4.27.2, 5.0.3 and 5.1 and I always had the pattern MAJOR.MINOR in the .uproject (patch number was never present). So I worked with this assumption.

Anyway I can take into account the custom version pattern as you propose, and make the version parsing less "restrictive".

**Comment by fdefelici** [comment]
Now can recognize the following semver pattern: MAJOR.MINOR.PATCH-LABEL where:
* MAJOR and MINOR stay mandatory 
* PATCH is optional
* LABEL is optional (separated by ''-")

**Comment by fdefelici** [comment]
@mklierman FUnreal v0.0.5 is out and should address your issue

**Comment by mklierman** [comment]
Thanks. I can confirm it worked
