### ISSUE TITLE
Allow to add custom templates

### ISSUE THREAD

**Issue by DrizztDoUrden** [fdefelici/vs-funreal#16]
I often create a LOT of files with similar structure. I'd like to be able to add custom templates to the extension without rebuilding it.

**Comment by fdefelici** [comment]
I was thinking to add this feature soon or later. Probably the time has come :)

**Comment by fdefelici** [comment]
Implemented feature that allow to add custom templates for: plugins, plugin modules, game modules and classes
Futhermore an dedicated extension menu and options page have been implemented to manage custom plugin

Documentation describing the new features and how to configure custom template has been written and accessible from  [README.md](https://github.com/fdefelici/vs-funreal/blob/3373013040715e524f02d8ee1b70165d5f04d4b7/README.md)

**Comment by fdefelici** [comment]
@DrizztDoUrde v0.2.0 is out, with the custom template feature
