### ISSUE TITLE
New plugin

### ISSUE THREAD

**Issue by DrizztDoUrden** [fdefelici/vs-funreal#17]
A feature to add a new empty plugin from visual studio would be useful.

**Comment by fdefelici** [comment]
Eventually you can add Blank plugin (the one you can create from UE Editor that is a plugin with a blank module) from VS right clicking on the game project (or alternatively from the Plugins folder if already exists) 

![image](https://github.com/fdefelici/vs-funreal/assets/24794993/a9c71dec-5959-4d24-aea2-65150b15c4d4)

Doesn't suite you?

**Comment by DrizztDoUrden** [comment]
Oh, sorry, didn't see that. Thank you! :)
