### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by imtrobin** [fdefelici/vs-funreal#25]
Reporting,  was using 0.1.0 before, working great, but noticed it was  not working today. There is no FUnreal context menu option anymore. The extension is still loaded, other unreal vs extensions work fine. How to debug?

**Comment by fdefelici** [comment]
Do you see FUnreal output window?

![image](https://github.com/fdefelici/vs-funreal/assets/24794993/16286d5b-72f9-438f-bc5f-9acb2203bc99)

**Comment by imtrobin** [comment]
actually, I  don't see  this,  your output log panel looks very  different from the default. Anyway, strangely, I rebuild the  c++ project, and now it shows. Not sure why it disappeearred previously.

**Comment by imtrobin** [comment]
thanks for the help

**Comment by imtrobin** [comment]
Ok, it happened again.  I can see FUnreal context menu on top project  but no FUnreal context menu when I rightclick on folders or files.

**Comment by fdefelici** [comment]
mmh very strange. This make me think that could exist some concurrency with other plugins. 

Do you use any other VS plugin for UE/C++ projects?

**Comment by imtrobin** [comment]
I have many  plugins in VS but the one with UE is the offical visual studio plugin from MS.

**Comment by imtrobin** [comment]
actually, now a rebuild doesn't fix it.. FUnreal context menu only appears  on the project, not folders/files,  I updated vs recently too.

**Comment by fdefelici** [comment]
If it's something related to plugins concurrency won't be determistic any actions (like the fully rebuild).

Just to narrow down the problem:
1) Which VS version you are updated to? (from Help -> About Microsoft Visual Studio)
2) Could you attach a print screen of the context menu on folders and files where you miss FUnreal?

**Comment by imtrobin** [comment]
17.8.3

Windows went to auto reboot while I was asleep , and  now it's working, just by opening  the project. Previously restarting VS didn't even work.

**Comment by fdefelici** [comment]
I've tested against same VS version 17.8.3 without any issue.

I think is something related to your workspace. And from what you described it seems that FUnreal always start, but there should be some other plugin - in no deterministic fashion - that "override" FUnreal menu item preventing them from showing up.

Could be very difficult to find this kind of conflict. Anyway if you gather more evidence in the future, let me know.
