### ISSUE TITLE
Unable to create Unreal Interface

### ISSUE THREAD

**Issue by ZeroComfort** [fdefelici/vs-funreal#6]
Upon trying to create and add a new Unreal Interface through FUnreal I get presented with the following error message:

![image](https://user-images.githubusercontent.com/22333120/208380469-6762bb28-904b-4a36-a726-971197856f90.png)
> [ERRO] Template not found for (sources, 5, tpl_class_unrealinterface)

Visual Studio 2022 (17.4.3)
Unreal Engine 5.0
FUnreal 0.0.5

**Comment by fdefelici** [comment]
Hi @ZeroComfort, thanks for reporting the issue.

FUnreal v0.0.7 has been published and should resolve the problem.

**Comment by ZeroComfort** [comment]
I can confirm it has been fixed. Thanks for the quick response!
